apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  containers:
  - name: con1
    image: wordpress:latest
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_NAME
      value: wordpress      # Database name (same as MYSQL_DATABASE in con2)
    - name: WORDPRESS_DB_USER
      value: root        # MySQL user (using root by default)
    - name: WORDPRESS_DB_PASSWORD
      value: test123     # Password (same as MYSQL_ROOT_PASSWORD in con2)
    command:
      - /bin/bash
      - -c
      - |
        apt-get update && apt-get install -y nano && \
        # Start the original WordPress entrypoint after installing nano
        docker-entrypoint.sh apache2-foreground
  - name: con2
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: test123      # MySQL root password
    - name: MYSQL_DATABASE
      value: testdb       # MySQL database name
    ports:
    - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30124
