#controlplane $ kubectl create secret generic testwp --from-literal wppass=test123 --dry-run=client -o yaml 
# to decode the encryption you can use controlplane $ echo dGVzdDEyMw== | base64 -d
# controlplane $ test123
apiVersion: v1
data:
  wppass: dGVzdDEyMw==
kind: Secret
metadata:
  creationTimestamp: null
  name: testwp
