#controlplane $ kubectl create secret generic mycert --from-file secretinfile.crt --dry-run=client -o yaml 
# there is a file which has sensitive information and we want to store that content in our secret. For that, we are using this file. 
apiVersion: v1
data:
  secretinfile.crt: dGhpcyBpcyBteSBjZXJ0IGZpbGUuLgo=
kind: Secret
metadata:
  creationTimestamp: null
  name: mycert
