apiVersion: v1
kind: Pod
metadata:
  name: wp
  labels:
    app: mywp
spec:
  containers:
  - name: con1
    image: wordpress:latest
    env:
    - name: WORDPRESS_DB_HOST
      value: wordpress
    - name: WORDPRESS_DB_USER
      value: root
    - name: WORDPRESS_DB_PASSWORD
      value: ### I want to get this password from the secret
      valueFrom:
        secretKeyRef:
          name: testwp  ### secret key
          key: wppass   ### secret value #we are calling is coming from the secret called testwp
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_TABLE_PREFIX
      value: wp_
