#controlplane $ kubectl create secret generic mycert --from-file secretinfile.crt --dry-run=client -o yaml 
apiVersion: v1
data:
  secretinfile.crt: dGhpcyBpcyBteSBjZXJ0IGZpbGUuLgo=
kind: Secret
metadata:
  creationTimestamp: null
  name: mycert
