### after the deployment of the configmap on the system, you can use this file to call the environment variables from the configMap
apiVersion: v1
kind: Pod
metadata:
  name: wp
  labels:
    app: mywp
spec:
  containers:
  - name: con1
    image: wordpress:latest
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: mywp # name of the config map, you can get this through kubectl get configmap or from the file from which you deployed (cm)
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  type: NodePort
  selector:
    app: mywp
  ports:
  - port: 80
    nodePort: 30123
