### You will have to create the devops namespace for this to work.
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: devops
spec:
  limits:
  - default: # this section defines default limits
      cpu: "300m"
      memory: "256Mi"
    defaultRequest: # this section defines default requests
      cpu: 100m
      memory: "64Mi"
    max: # max and min define the limit range
      cpu: "1"
    min:
      cpu: 100m
    type: Container

