### before this I created the kubectl create sa orange 
### sa is a service account
### for more information check the notes in the RBAC
apiVersion: v1
kind: Secret
metadata:
    name: orange
    annotations: ## is kind of the label but will be used for some of the kubernetes plugins or objects to enable or disable some settings
      kubernetes.io/service-account.name: orange # we are defining annotation here is that we are mapping it to service account name called orange
type: kubernetes.io/service-account-token # service account token
