apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep-hpath
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: con1
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: myvol
          mountPath: /data
      - name: con2
        image: tomcat:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: myvol
          mountPath: /mydata
      volumes:
      - name: myvol
        hostPath:
          path: /appdata # this directory will be created on the hostmachine and whenever my pod is scheduled and my data will be stored in this path
